### ISSUE TITLE
MacOS py3.9

### ISSUE THREAD

**Issue by gogobd** [3DSinghVFX/an_extra_nodes#1]
Hi!

Thank you ver much for putting so much great work into this great project. Unfortunately I can't use the latest release on MacOS, maybe because latest Blender 2.93 uses Python 3.9. The build from graphicall (that have a note about Python3.9 in the changes) gives me an error:

```
Exception in module register(): /Users/georg/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/__init__.py
Traceback (most recent call last):
  File "/Users/georg/Documents/Work/git.blender.org/build_darwin/bin/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/Users/georg/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/__init__.py", line 172, in register
    auto_load.register()
  File "/Users/georg/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/auto_load.py", line 28, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "an_IntegerListSocket" registration error: display could not register
```

Is there anything I could try to get it running?
I was trying in a source build of Blender today and also in the Alpha Download from the Blender Website.

**Comment by gogobd** [comment]
Got it to run in Blender 2.92 (Release) by using Animation Nodes releases from YOUR repository and Extra Nodes from here, too. The py3.9 issue probably remains though.

**Comment by 3DSinghVFX** [comment]
@gogobd Hi. Are you using the *[Animation Nodes + Extra Nodes](https://github.com/3DSinghVFX/animation_nodes)* or this addon *AN Extra Nodes* which is an extension for Animation Nodes?

If you are using *AN Extra Nodes* addon which is not updated for Python 3.9 yet but I'll do that soon.
However, if you are using the *[Animation Nodes + Extra Nodes](https://github.com/3DSinghVFX/animation_nodes)*, then I think this issue is already reported https://github.com/3DSinghVFX/animation_nodes/issues/162

**Comment by gogobd** [comment]
I was trying AN + Extra, so please consider this report a duplicate. The separate installation of AN and Extra nodes into Blender 2.92 (release) went perfectly well.
