### ISSUE TITLE
How to use Extra nod ein Blender 2.93 with python 3.9 ?

### ISSUE THREAD

**Issue by kebab03** [3DSinghVFX/an_extra_nodes#3]
Can't install the extra node  with Blender, although I use AN 2.2.2  in  blender 2.93.3  , because it use python 3.9  & An 1.0.0 in  Blender 2.83.20  which use Python 3.7?Please help to make the correction

**Comment by 3DSinghVFX** [comment]
Hi. I suggest you install the Animation Nodes + Extra Nodes addon instead of this because that has the latest changes:

All releases for different Blender Versions: https://github.com/3DSinghVFX/animation_nodes/releases
For Blender3.3x, use the LATEST build: https://github.com/3DSinghVFX/animation_nodes/releases/tag/extranodes-cd-build
